BookStoreApp/Controllers/BookController.cs
using BookStoreApp.Repository.Interface;
using BookStoreApp.Repository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BookStoreApp.Controllers
{
    public class BookController : Controller
    {
		private IRepository repo;
		public BookController(IRepository _repo)
		{
			this.repo = _repo;
		}
        // GET: Book
        public ActionResult Index()
        {
            return View();
        }
		public async Task<bool> Create(Books book)
		{
			if (ModelState.IsValid)
			{
				return await repo.AddBook(book);
			}
			return false;
		}

    }
}

BookStoreApp/Controllers/StoreController.cs
using BookStoreApp.Repository.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BookStoreApp.Controllers
{
	public class StoreController : Controller
	{
		private IRepository repo;
		public StoreController(IRepository _repo)
		{
			this.repo = _repo;
		}
		// GET: Store
		public ActionResult Index()
		{
			return View();
		}
		public ActionResult GenreList()
		{
			var genres = repo.GetGenres();//this method is not using async because Child Action is not supported async
			return PartialView(genres);
		}
		public async Task<ActionResult> Browse(string genre)
		{
			var book = await repo.GetBooks(genre);
			return View(book);
		}
	}
}

BookStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="col-lg-12">
        <div class="navbar navbar-inverse" style="margin-top: -4%;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("DashBoard", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <a href="@Url.Action("Index", "Book")" class="btn btn-info" style="margin-top: 12px;">Add Book</a>
                </div>
                <div class="navbar-collapse collapse">
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
            @Html.TextBox("Search", null, new
       {
           @class = "form-control col-lg-12 col-lg-offset-3",
           style = "min-width:50%;margin-top: -11px;margin-bottom: 28px; ",
           placeholder = "Search Title and Author"
       })

        </div>
        @{Html.RenderAction("GenreList", "Store");}
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>